# Generated by Django 5.2.5 on 2025-09-08 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='number')),
                ('ordered_at', models.DateTimeField(auto_now_add=True, verbose_name='ordered at')),
                ('meals', models.ManyToManyField(to='meals.meal', verbose_name='meals')),
            ],
        ),
    ]
