# Generated by Django 5.2.5 on 2025-09-08 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.IntegerField(default=1, verbose_name='number'),
        ),
    ]
