# Generated by Django 5.2.5 on 2025-09-08 08:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='meal name')),
                ('base_price', models.DecimalField(decimal_places=2, default=1.0, max_digits=8, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='base price')),
                ('preparation_time', models.PositiveIntegerField(default=7, validators=[django.core.validators.MinValueValidator(7)], verbose_name='preparation time (seconds)')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='authentication.restaurant', verbose_name='restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='OptionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='group name')),
                ('allow_multiple', models.BooleanField(default=False, verbose_name='allow multiple choices')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_groups', to='meals.meal', verbose_name='meal')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='option name')),
                ('extra_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='extra price')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='meals.optiongroup', verbose_name='option group')),
            ],
        ),
    ]
