# Generated by Django 5.2.5 on 2025-09-12 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='meals/', verbose_name='image'),
        ),
    ]
